name: Backup Bitbucket to GitHub

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Bitbucket Repo (mirror)
        run: |
          set -e
          git clone --mirror https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/hitarth-dev/demo.git

      - name: Push to GitHub (mirror)
        run: |
          set -e
          cd demo.git
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hitarthsh/demo-1.git
          git push --mirror github
